# Default initial positions for kr240r2900_2's ros2_control fake system

initial_positions:
  endeffector_plug_joint_1: 0
  endeffector_plug_joint_2: 0
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0
  omnibase_pris_x_joint: 0
  omnibase_pris_y_joint: 0
  omnibase_rev_joint: 0
  agv_pris_x_joint: 0
  agv_pris_y_joint: 0
  agv_rev_joint: 0
  