# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    gains:
      joint_1: { p: 100.0, i: 0.01, d: 1.0 }
      joint_2: { p: 100.0, i: 0.01, d: 1.0 }
      joint_3: { p: 100.0, i: 0.01, d: 1.0 }
      joint_4: { p: 100.0, i: 0.01, d: 1.0 }
      joint_5: { p: 100.0, i: 0.01, d: 1.0 }
      joint_6: { p: 100.0, i: 0.01, d: 1.0 }